modLoader="javafml"
loaderVersion="[41,)"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=controllable"
issueTrackerURL="https://github.com/MrCrayfish/Controllable/issues"
displayURL="https://mrcrayfish.com/mods?id=controllable"
logoFile="controllable_logo.png"
authors="MrCrayfish"
license="GNU General Public License 3.0"

[[mods]]
modId="controllable"
version="0.16.5"
displayName="Controllable"
description="Adds the ability to use a controller to play Minecraft"

[[dependencies.controllable]]
   modId="forge"
   mandatory=true
   versionRange="[43.0.11,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="jei"
   mandatory=false
   versionRange="[11.2.0.246,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="configured"
   mandatory=false
   versionRange="[1.5.6,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="catalogue"
   mandatory=false
   versionRange="[1.6.3,)"
   ordering="NONE"
   side="CLIENT"

[modproperties.controllable]
   catalogueImageIcon="controllable_icon.png"
   configuredBackground="minecraft:textures/block/cobblestone.png"