modLoader="javafml"
loaderVersion="[41,)"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=controllable"
issueTrackerURL="https://github.com/MrCrayfish/Controllable/issues"
displayURL="https://mrcrayfish.com/mods?id=controllable"
logoFile="controllable_logo.png"
authors="MrCrayfish"
license="GNU General Public License 3.0"

[[mods]]
modId="controllable"
version="0.16.3"
displayName="Controllable"
description="Adds the ability to use a controller to play Minecraft"

[[dependencies.controllable]]
   modId="forge"
   mandatory=true
   versionRange="[42.0.1,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.1,1.20)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="jei"
   mandatory=false
   versionRange="[9.5.2,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="configured"
   mandatory=false
   versionRange="[1.5.0,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="catalogue"
   mandatory=false
   versionRange="[1.6.0,)"
   ordering="NONE"
   side="CLIENT"

[modproperties.controllable]
   catalogueImageIcon="controllable_icon.png"
   configuredBackground="minecraft:textures/block/cobblestone.png"