modLoader="javafml"
loaderVersion="[41,)"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=controllable"
issueTrackerURL="https://github.com/MrCrayfish/Controllable/issues"
displayURL="https://mrcrayfish.com/mods?id=controllable"
logoFile="controllable_logo.png"
authors="MrCrayfish"
license="GNU General Public License 3.0"

[[mods]]
modId="controllable"
version="0.17.0"
displayName="Controllable"
description="Adds the ability to use a controller to play Minecraft"

[[dependencies.controllable]]
   modId="forge"
   mandatory=true
   versionRange="[44.0.37,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.3,1.20)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="jei"
   mandatory=false
   versionRange="[11.5.0.297,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="configured"
   mandatory=false
   versionRange="[2.0.2,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="catalogue"
   mandatory=false
   versionRange="[1.7.0,)"
   ordering="NONE"
   side="CLIENT"

[modproperties.controllable]
   catalogueImageIcon="controllable_icon.png"
   catalogueBackground="controllable_background.png"
   configuredBackground="minecraft:textures/block/cobblestone.png"